# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Alertmanager installation tasks
  when: alertmanager_enabled | bool
  tags:
    - setup-all
    - setup-alertmanager
    - install-all
    - install-alertmanager
  block:
    - name: Validate Alertmanager configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Prepare HTTP Basic authentication for Alertmanager
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"
    - name: Install Alertmanager
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Alertmanager uninstallation tasks
  when: not alertmanager_enabled | bool
  tags:
    - setup-all
    - setup-alertmanager
  block:
    - name: Uninstall Alertmanager
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
