# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Alertmanager systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ alertmanager_identifier }}.service"
  register: alertmanager_service_stat

- name: Uninstall Alertmanager systemd services and files
  when: alertmanager_service_stat.stat.exists | bool
  block:
    - name: Ensure Alertmanager systemd service is stopped
      ansible.builtin.service:
        name: "{{ alertmanager_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Alertmanager systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ alertmanager_identifier }}.service"
        state: absent

    - name: Ensure Alertmanager path does not exist
      ansible.builtin.file:
        path: "{{ alertmanager_base_path }}"
        state: absent
