# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Alertmanager systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ alertmanager_identifier }}.service"
  register: alertmanager_service_stat

- name: Uninstall Alertmanager systemd services and files
  when: alertmanager_service_stat.stat.exists | bool
  block:
    - name: Ensure Alertmanager systemd service is stopped
      ansible.builtin.service:
        name: "{{ alertmanager_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Alertmanager systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ alertmanager_identifier }}.service"
        state: absent

    - name: Ensure Alertmanager container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ alertmanager_container_network }}"
        state: absent

    - name: Ensure Alertmanager container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ alertmanager_container_network }}
      register: network_deletion_result
      changed_when: alertmanager_container_network in network_deletion_result.stdout

    - name: Ensure Alertmanager path does not exist
      ansible.builtin.file:
        path: "{{ alertmanager_base_path }}"
        state: absent
